import React from 'react'
import Star from '../assets/star.png'
import LightWoman from '../assets/lightWoman.png'
import Perfect from '../assets/perfect.png'
import BrownWoman from '../assets/brownWoman.png'
import LightMale from '../assets/lightMan.png'
import BrownMan from '../assets/brownMan.png'

const users = ([
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
    {name:'Emma',
    city:'Dallas, TX',
    price: 1100,
    active: "2 DAYS AGO",
    perfect: true,
    female: true,
    color: 'light',
    type: 'Roommate'},
    {name:'Brit',
    city:'Little Rock, AR',
    price: 500,
    active: "1 HOUR AGO",
    perfect: false,
    female: true,
    color: 'brown',
    type: 'Roommate'},
    {name:'Mike',
    city:'New York, New York',
    price: 1900,
    active: "9 HOUR AGO",
    perfect: false,
    female: false,
    color: 'light',
    type: 'Roommate'},
    {name:'Joe',
    city:'Frisco, TX',
    price: 1300,
    active: "7 DAYS AGO",
    perfect: true,
    female: false,
    color: 'brown',
    type: 'Roommate'},
])


const Hero = (props) => {
  return (
    <div className='pl-[10%] pr-[10%] w-full flex flex-wrap justify-center'>
        {users.map((user,i)=>{
            return(
                <div key={i} className="flex flex-col shadow-md hover:shadow-lg rounded-sm cursor-pointer mr-4 mb-4">
                    <div className="top relative">
                        <img className='h-[150px] w-[225px] object-cover' src={user.female?user.color==='light'?LightWoman:BrownWoman:user.color==='light'?LightMale:BrownMan} alt='man or woman' />
                        <img className='h-8 absolute top-2 left-2 z-[2]' src={Star} alt="star" />
                        {user.perfect?<img className='absolute w-[106px] top-0 right-0' src={Perfect} alt='perfect'/>:''}
                    </div>
                    <div className="bottom flex flex-col p-5">
                        <span className='font-bold text-blue-500 leading-4'>${user.price} <span className='text-black'>Max Rent</span></span>
                        <p className='leading-4 font-light'>{user.type} available in</p>
                        <p className='font-bold leading-4'>{user.city}</p>
                        <h1 className='text-3xl font-semibold mt-3 mb-3'>{user.name}</h1>
                        <span className='text-xs'>ACTIVE <span className='font-bold'>{user.active}</span></span>
                    </div>
                </div>
            
            )
        })}
    </div>
  )
}

export default Hero